### PR TITLE
Update metadata overlay and possible fix for #43

### LINKED ISSUE #43: Text immediately following the line "--text follows this line--"
It will be easier to show in a screenshot.

That is, the text immediately following the line `--text follows this line--` is written to the metadata.

### PR DESCRIPTION
**Pull request by qingshuizheng**
1. update metadata overlay's read-only property for better interaction
2. Possible fix #43

More details see commit messages.

### CODE REVIEW

**Review by ahyatt — APPROVED** [review]

**Comment by ahyatt** [comment]
Thank you for these changes, which look like interesting fixes!  I like the ideas here.  I'm going to try these out, but as written, they look like they should work.

**Comment by ahyatt** [comment]
A few comments (I probably should have tried this out before merging):

I'm trying this out now, but it seems like `(propertize "\n" 'display "--text follows this line--\n\n" 'read-only t 'rear-nonsticky t)` doesn't actually display "--text follows this line--", at least for me.    I'm assuming this works for you, so I'm not sure what the difference is.  I'm using Emacs 29 built a few months ago, perhaps this is functionality newer than that?

Also, two tests related to the overlay no longer pass, which needs to be fixed.  Would you mind fixing those tests?

I'm not crazy about the warning about read-only when trying to delete backwards from the first actual line of text.  Still, it does work, and `org-insert-headline` works now.

The label fixes work well, but I can press return on the first editable character and it beeps and complains about text-only properties but does insert the newline.  It probably shouldn't; but then again, it almost certainly didn't protect against this before either.

All in all, these still look promising, and I'm interested to see if we can fix these issues - if not, we may have to revert the parts that are problematic (probably just the "--text follows this line--" part.

**Comment by qingshuizheng** [comment]
Ahh, I'm coming late. 

This display property seems existing before I came to Emacs 3 years ago, but I'm not sure. I'm currently using Emacs 30 built one month ago, since it just branched out not long ago from emacs 29, I assumed there's no too much difference there. I can ask some others to test it out tho.

> (propertize "\n" 'display "--text follows this line--\n\n" 'read-only t 'rear-nonsticky t)

It should be inserted with `(insert &args)`, dont' miss that:

```elisp
(insert
 (propertize
  "\n"
  'display "--text follows this line--\n\n"
  'read-only t
  'rear-nonsticky t))
```

Here's a dummy gif: 
iShot_2023-05-09_17 18 22


> Would you mind fixing those tests?

TBH I never write any test before, I can give it a go, but no promise.

**Comment by ahyatt** [comment]
Your example works perfectly, but for some reason your change is not working, and I have no idea why!  I'm going to spend a bit more time looking into it.  I appreciate your demonstration of this and further explanations.

Your new `ekg--metadata-string` does work, although it still has the same issue I mentioned: if I put the cursor on the first character of the field value, and press return, it will complain about a read-only property but then puts the field value on the following line.  This isn't a big deal, and it probably has no good solution, but just wanted to mention it.

**Pull request merged**
