### PR TITLE
kill window on capture abort

### PR DESCRIPTION
**Pull request by QiangF**
The window layout should be restored.

### CODE REVIEW

**Comment by ahyatt** [comment]
Thank you for your contribution!  I'm curious why this is needed, though - with https://github.com/ahyatt/ekg/commit/789cb6d954e0b31f8c25cc0bfa84ba812820f5cf, we no longer open the notes in a different window - so theoretically we shouldn't need to kill the window.  For example, if the user has two windows, and opens notes in one of them, I think it'd be a mistake to kill that window when quiting out of the notes buffer.  What do you think?

**Comment by qingshuizheng** [comment]
> 1. highlighted with hl-line face, which is quite distracting

Quite agree on this. I'd like to disable it by default.

**Comment by ahyatt** [comment]
Without hl-line-mode, though, how do you know what the current note is?  There needs to be some visual indication.

As far as the behavior of creating windows or not (and then killing them on quitting out), perhaps the behavior can be configured.  Let me see if there's some standard practice that I might be missing here.

**Comment by ahyatt** [comment]
Thank you for bringing up these points, though - I appreciate the pull request.  I'm not sure what the best solution is yet, but I'll continue to think about this.

**Pull request closed without merging**
